kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: pytest-workflow-trial
  namespace: testkube
  labels:
    core-tests: workflows
    tool: pytest
spec:
  content:
    git:
      uri: https://github.com/bchmura-af/testkube
      revision: develop
      paths:
      - /__TEST__/workflows/pytest

  container:
    workingDir: /data/repo/__TEST__/workflows/pytest
    image: afbartoszchmura/testing:pytest-latest
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
  job:
    activeDeadlineSeconds: 300

  steps:
    # - name: Install stuff
    #   image: python:3.8.17-alpine3.18
    #   steps:
    #   - name: Pip
    #     shell: python3 -m pip install --no-cache-dir --upgrade pip; python3 -m pip install --no-cache-dir --upgrade pipenv; python3 -m pip install --no-cache-dir --upgrade requests; python3 -m pip install --no-cache-dir --upgrade pytest

    - name: Run tests
      shell: python3 -m pytest passed_sample.py
